# Fuses all target sources in a single file.

function(fuse_target _target_name)

  set(output_file_name "${_target_name}.cc")
  set(output_file "${CMAKE_SOURCE_DIR}/src_fused/${output_file_name}")
  set(temp_output_file "${ozz_temp_directory}/${output_file_name}.in")

  # Start with new content
  string(CONCAT output_content "" "// This file is autogenerated from ${_target_name} target sources.\n\n")

  # Get all target sources.
  get_property(target_source_files TARGET ${_target_name} PROPERTY SOURCES)

  # Concat all sources to the output.
  foreach(src_file ${target_source_files})
    get_filename_component(src_file_ext ${src_file} EXT)

    # Handle source files.
    if(src_file_ext STREQUAL ".cc")
      file(READ "${CMAKE_CURRENT_LIST_DIR}/${src_file}" src_file_content)

      string(CONCAT output_content "${output_content}" "// Including ${src_file} file.\n\n")
      string(CONCAT output_content "${output_content}" "${src_file_content}\n")

    endif()
  endforeach()

  # Handle private include files (they are not prefixed by "ozz/").
  string(REGEX MATCHALL "#include \"[\^\"ozz\"]([^\"]+)\"" internal_include_lines ${output_content})

  foreach(internal_include_line ${internal_include_lines})

    STRING(REGEX REPLACE "#include \"([^\"]+)\"" "\\1" internal_include_file "${internal_include_line}" )

    file(READ "${CMAKE_SOURCE_DIR}/src/${internal_include_file}" internal_src_file_content)

    string(REPLACE "${internal_include_line}" "\n// Includes internal include file ${internal_include_file}\n\n${internal_src_file_content}" output_content "${output_content}")

  endforeach()

  # Final ouput. Uses configure_file to avoid rewritting the file if it hasn't change (avoid dependencies rebuild).
  file(WRITE "${temp_output_file}" "${output_content}")
  configure_file("${temp_output_file}" "${output_file}" COPYONLY)

endfunction()
