{
  "skeleton":
  {
    "filename":"${ozz_temp_directory}/fbx_propreties_skeleton.ozz"
  },
  "animations":
  [
    {
      "filename":"${ozz_temp_directory}/fbx_properties_animation_${CMAKE_CURRENT_LIST_LINE}.ozz",
      "tracks":
      [
        {
          "properties":
          [
            {
              "filename":"${ozz_temp_directory}/fbx_properties_track1_*.ozz",
              "joint_name":"*",
              "property_name":"ozz_*",
              "type":1
            },
            {
              "filename":"${ozz_temp_directory}/fbx_properties_track2_*.ozz",
              "joint_name":"*",
              "property_name":"ozz_*",
              "type":2
            },
            {
              "filename":"${ozz_temp_directory}/fbx_properties_track3_*.ozz",
              "joint_name":"*",
              "property_name":"ozz_*",
              "type":3
            },
            {
              "filename":"${ozz_temp_directory}/fbx_properties_track4_*.ozz",
              "joint_name":"*",
              "property_name":"ozz_*",
              "type":4
            }
          ]
        }
      ]
    }
  ]
}