name: Windows
on: [push, pull_request]
jobs:
  build:
    runs-on: windows-latest 
    strategy:
      fail-fast: false
      matrix:
        build_type: [Debug]
        option: [default, ref, shared, no_fbx]
        include:
          - build_type: Release
            option: default
    steps:
    - uses: actions/checkout@v4
    
    - name: Install fbx sdk
      if: matrix.option != 'no_fbx'
      run: |
        md fbx
        cd fbx
        Start-BitsTransfer -Source 'https://damassets.autodesk.net/content/dam/autodesk/www/adn/fbx/2020-3-4/fbx202034_fbxsdk_vs2022_win.exe' -Destination 'fbxsdk.exe'
        Start-Process -FilePath 'fbxsdk.exe' /S -Wait
        cd ..
    
    - name: Configure
      # Configure CMake in a 'build' subdirectory.
      run: |
        cmake --version
        cmake -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=${{matrix.build_type}} -DBUILD_SHARED_LIBS=${{matrix.option == 'shared'}} -Dozz_build_tests=${{matrix.option != 'no_tests'}} -Dozz_build_simd_ref=${{matrix.option == 'ref'}} -Dozz_build_samples=${{matrix.option != 'no_sample'}} -Dozz_build_data=${{matrix.option != 'no_data'}} -Dozz_build_gltf=${{matrix.option != 'no_gltf'}}

    - name: Build
      # Build your program with the given configuration
      run: cmake --build ${{github.workspace}}/build --config ${{matrix.build_type}} --use-stderr -j

    - name: Test
      working-directory: ${{github.workspace}}/build
      # Execute tests defined by the CMake configuration.
      run: ctest -C ${{matrix.build_type}} --output-on-failure
